# Generated by Django 2.1.4 on 2018-12-22 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='Team',
            new_name='team',
        ),
        migrations.AddField(
            model_name='team',
            name='puzzles_solved',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='rank',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='team',
            name='password',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='team',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
